MODEL:
  TYPE: mobilenetv2_legonas_lw
  ARCH_JSON: configs/nas/imagenet_arch_p16_g8_ng50_nb5.json
  NUM_CLASSES: 1000
  HEADS:
    NAME: "LinearHead"
    NUM_CLASSES: 1000
    IN_FEAT: 1280
    REDUCTION_DIM: 960
    POOL_LAYER: "avgpool"
    CLS_LAYER: "linear"
    MARGIN: 0.1
    SCALE: 30
  LOSSES:
    LABEL_SMOOTHING: 0.1
BN:
  ZERO_INIT_FINAL_GAMMA: True
OPTIM:
  BASE_LR: 0.04
  LR_POLICY: cos
  STEPS: [0, 30, 60, 90]
  LR_MULT: 0.1
  MAX_EPOCH: 300
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.00002
  WARMUP_EPOCHS: 0
TRAIN:
  DATASET: imagenet
  SPLIT: train
  BATCH_SIZE: 256
  IM_SIZE: 224
  CHECKPOINT_PERIOD: 1
  EVAL_PERIOD: 1
  EMA_FLAG: False
  DATA_FORMAT: parquet
  DATA_ROOT: /mnt/sda/weizixiang/wk/data/imagenet_v2/datasets--imagenet-1k/data
TEST:
  DATASET: imagenet
  SPLIT: validation
  BATCH_SIZE: 128
  IM_SIZE: 256
  DATA_FORMAT: parquet
  DATA_ROOT: /mnt/sda/weizixiang/wk/data/imagenet_v2/datasets--imagenet-1k/data
NUM_GPUS: 8
DATA_LOADER:
  NUM_WORKERS: 4
  MIXUP_ALPHA: 0.2
  CUTMIX_ALPHA: 0.2
CUDNN:
  BENCHMARK: True
OUT_DIR: .
LOG_DEST: file
