MODEL:
  TYPE: mobilenetv2_nas
  NUM_CLASSES: 101
  OP_CODES: [15, 14, 7, 6, 14, 15, 15, 10, 12, 11, 12, 4, 2, 13, 12, 0, 15, 1, 1, 12, 3]
  WIDTH_CODES: [1, 1, 1, 1, 1, 0, 0]
  HEADS:
    NAME: "LinearHead"
    NUM_CLASSES: 101
    IN_FEAT: 1280
    REDUCTION_DIM: 960
    POOL_LAYER: "avgpool"
    CLS_LAYER: "linear"
    MARGIN: 0.1
    SCALE: 30
  LOSSES:
    LABEL_SMOOTHING: 0.1
BN:
  ZERO_INIT_FINAL_GAMMA: True
OPTIM:
  BASE_LR: 0.008
  LR_POLICY: cos
  STEPS: [0, 30, 60, 90]
  LR_MULT: 0.1
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.00002
  WARMUP_EPOCHS: 5
TRAIN:
  DATASET: food101
  SPLIT: train
  BATCH_SIZE: 512
  IM_SIZE: 224
  CHECKPOINT_PERIOD: 1
  EVAL_PERIOD: 1
  EMA_FLAG: False
  WEIGHTS: ./pretrained/model_epoch_0296_570m_v21.pyth
TEST:
  DATASET: food101
  SPLIT: validation
  BATCH_SIZE: 256
  IM_SIZE: 256
NUM_GPUS: 4
DATA_LOADER:
  NUM_WORKERS: 16
  MIXUP_ALPHA: 0.2
  CUTMIX_ALPHA: 0.2
CUDNN:
  BENCHMARK: True
OUT_DIR: .
LOG_DEST: file
